#!/bin/bash
sudo su -
apt update -y
apt install -y openjdk-17-jdk

curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null

apt update -y
apt install jenkins -y 
apt install git -y
systemctl enable jenkins
systemctl start jenkins

wget https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
apt install unzip -y
unzip terraform_1.9.5_linux_amd64.zip

mv terraform /usr/local/bin/
terraform -v
